application: graphgroop
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always
- url: /js
  static_dir: static/js
- url: /partials
  static_dir: static/partials
- url: /.*
  script: GG.app
- url: /_ah/spi/.*
  script: GG.app
libraries:
- name: endpoints
  version: 1.0

- name: pycrypto
  version: latest

- name: numpy
  version: "1.6.1"
inbound_services:
- mail

builtins:
- remote_api: on
